; TOS launcher based on the original ELITE.S loading sequence.
; LOADER.IMG is linked at $11e00, as specified by the original LOADER.LNK.
; boot-config.inc is generated by build.py from the actual linked program.
    include "boot-config.inc"
    section text,code

start:
    lea launcher_end(pc),a0
    cmpa.l #loader_address,a0
    bhs memory_error
    move.l 4(sp),a0              ; GEMDOS basepage
    move.l 4(a0),d0              ; end of this process's TPA
    cmp.l #required_ram,d0
    blo memory_error

    ifd auto_start
    pea root_path(pc)
    move.w #$3b,-(sp)            ; Dsetpath: AUTO data stays in the boot drive root
    trap #1
    addq.l #6,sp
    tst.l d0
    bmi load_error
    endif

    clr.w -(sp)
    pea loader_name(pc)
    move.w #$3d,-(sp)            ; Fopen(name, read-only)
    trap #1
    addq.l #8,sp
    tst.l d0
    bmi load_error
    move.w d0,d7
    move.l #loader_address,-(sp)
    move.l #loader_size,-(sp)
    move.w d7,-(sp)
    move.w #$3f,-(sp)            ; Fread(handle, size, address)
    trap #1
    lea 12(sp),sp
    move.l d0,d6
    move.w d7,-(sp)
    move.w #$3e,-(sp)            ; Fclose(handle)
    trap #1
    addq.l #4,sp
    cmp.l #loader_size,d6
    bne load_error
    jmp loader_address

memory_error:
    pea memory_message(pc)
    bra.s show_error
load_error:
    pea load_message(pc)
show_error:
    move.w #9,-(sp)              ; Cconws, NUL-terminated (GEMDOS, not DOS)
    trap #1
    addq.l #6,sp
    move.w #7,-(sp)              ; Crawcin
    trap #1
    addq.l #2,sp
    move.w #1,-(sp)
    move.w #$4c,-(sp)            ; Pterm(1)
    trap #1

    ifd auto_start
root_path: dc.b 92,0            ; backslash, current drive root
    endif
loader_name: dc.b 'LOADER.IMG',0
memory_message:
    dc.b 'Elite needs free low memory and',13,10
    dc.b 'at least 512 KB RAM. Boot a plain',13,10
    dc.b 'ST desktop without accessories.',13,10
    dc.b 'Press a key.',13,10,0
load_message:
    dc.b 'Cannot read LOADER.IMG.',13,10
    ifd auto_start
    dc.b 'Keep all game data in the root',13,10
    dc.b 'of the boot disk. Press a key.',13,10,0
    else
    dc.b 'Keep ELITE.TOS and all game files',13,10
    dc.b 'in the same directory. Press a key.',13,10,0
    endif
    even
launcher_end:
