"""Generate the immutable white-star catalogue and its conservative cone tree.

Run explicitly after changing the catalogue; game builds consume asm/sky.dat.
No game random state, floating-point runtime or per-frame generation is needed.
"""
from pathlib import Path
import math
import random

COUNT = 1024
LEAF = 4
UNIT = 16384
# Half-viewport extents of the widest build (PAL, x_size 320 by y_size 168)
# over the 512-pixel projection scale. A wider cone only culls less, so this
# value stays conservative for a shorter NTSC viewport.
FOV = math.atan(math.hypot(160, 84) / 512) + math.radians(0.25)


def catalogue():
    rng = random.Random(0x454C495445)
    points = []
    minimum_dot = math.cos(math.radians(2.2))
    while len(points) < COUNT:
        z = rng.uniform(-1, 1)
        angle = rng.uniform(0, math.tau)
        radius = math.sqrt(1 - z*z)
        point = (radius*math.cos(angle), radius*math.sin(angle), z)
        if any(sum(a*b for a, b in zip(point, p)) > minimum_dot for p in points):
            continue
        points.append(point)
    return [tuple(round(c * UNIT) for c in p) for p in points]


def tree(points):
    centre = [sum(p[i] for p in points) for i in range(3)]
    length = math.sqrt(sum(v*v for v in centre))
    centre = [v/length for v in centre] if length else [0, 0, 1]
    radius = max(math.acos(max(-1, min(1, sum(c*v for c, v in zip(centre, p)) /
                 math.sqrt(sum(v*v for v in p))))) for p in points)
    threshold = math.floor(math.cos(min(math.pi, radius + FOV)) * UNIT**2) - 65536
    axis = tuple(round(c * UNIT) for c in centre)
    if len(points) == LEAF:
        body = ['    dc.w ' + ','.join(map(str, p)) for p in points]
        skip = -LEAF * 6
        size = 12 + LEAF * 6
    else:
        split = max(range(3), key=lambda i: max(p[i] for p in points)-min(p[i] for p in points))
        points = sorted(points, key=lambda p: p[split])
        left, ls = tree(points[:len(points)//2])
        right, rs = tree(points[len(points)//2:])
        body = left + right
        skip = ls + rs
        size = 12 + skip
    return (['    dc.w ' + ','.join(map(str, axis)),
             f'    dc.l {threshold}', f'    dc.w {skip}'] + body), size


def generate():
    body, size = tree(catalogue())
    return ('; Generated by tools/make_sky.py. Seeded catalogue; do not hand-edit.\n'
            f'; {COUNT} stars, {size} bytes including cone-tree indexing.\n'
            '; Node: Q14 direction (3 words), Q28 threshold (long), skip (word).\n'
            '; Positive skip = rejected subtree bytes; negative = leaf bytes.\n'
            f'sky_leaf_count: equ {LEAF}\n'
            'sky_catalogue:\n' + '\n'.join(body) + '\nsky_catalogue_end:\n')


if __name__ == '__main__':
    target = Path(__file__).resolve().parents[1] / 'asm/sky.dat'
    target.write_text(generate(), encoding='ascii')
    print(target)
